version: 2 

models:
  - name: product_src_table
    description: Cleansed table which contain airbnb listings
    columns:
      - name: product_id
        description: Primary Key for the listings 
        tests:
          - unique
          - not_null

      # - name: host_id
      #   description: Host id it is the refrance to hosts data 
      #   tests:
      #     - not_null
      #     - relationships:
      #         to: ref('dim_hosts')
      #         field: host_id

      # - name: room_type
      #   tests:
      #     - accepted_values:
      #         values: ['Entire home/apt',
      #                   'Private room',
      #                   'Shared room',
      #                   'Hotel room']


      # - name: minimum_nights
      #   description: '{{doc("dim_listing_cleansed__minimum_nights")}}'
      #   tests:
      #     - positive_value