version: 2 
sources:
  - name: source_v1
    database: dbt-setup-01 
    schema: retail_data
    tables:
      - name: product
        identifier: scr_product        

      - name: transaction
      
